# Generated by Django 3.1.6 on 2021-02-17 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0012_auto_20210218_0107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_category',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='user_category',
            old_name='user_id',
            new_name='user',
        ),
    ]
