# Generated by Django 3.1.6 on 2021-02-17 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0013_auto_20210218_0115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='content',
            new_name='name',
        ),
        migrations.AddField(
            model_name='todo',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='todos.category'),
            preserve_default=False,
        ),
    ]
