# Generated by Django 3.1.6 on 2021-02-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0014_auto_20210218_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='pic',
            field=models.CharField(default='image/pic04.jpg', max_length=100),
        ),
    ]
