# Generated by Django 3.1.6 on 2021-02-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0015_category_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='pic',
            field=models.CharField(default='images/pic04.jpg', max_length=100),
        ),
    ]
