# Generated by Django 3.1.6 on 2021-02-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0016_auto_20210220_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='pic',
            field=models.CharField(default='/static/images/pic04.jpg', max_length=100),
        ),
    ]
