# Generated by Django 3.1.6 on 2021-02-20 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0017_auto_20210220_0125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='user_id',
            new_name='user',
        ),
    ]
