# Generated by Django 3.1.6 on 2021-02-22 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0021_auto_20210220_1912'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Category',
        ),
    ]
