# Generated by Django 3.1.6 on 2021-02-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0022_delete_user_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='pic',
            field=models.ImageField(default='/static/images/pic04.jpg', upload_to='category_pics'),
        ),
    ]
