# Generated by Django 3.1.6 on 2021-02-23 15:55

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0023_auto_20210223_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='pic',
            field=imagekit.models.fields.ProcessedImageField(default='categories/pic01.jpg', upload_to='categorypics'),
        ),
    ]
