# Generated by Django 3.1.6 on 2021-02-24 12:31

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0024_auto_20210224_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='pic',
            field=imagekit.models.fields.ProcessedImageField(default='categorypics/pic01.jpg', upload_to='categorypics'),
        ),
    ]
