# Generated by Django 3.1.6 on 2021-02-24 12:31

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='title', max_length=60)),
                ('description', models.CharField(blank=True, help_text='description', max_length=300)),
                ('thumbnail', imagekit.models.fields.ProcessedImageField(default='categorypics/pic01.jpg', upload_to='articleimgs')),
                ('content', models.TextField(help_text='content')),
            ],
        ),
    ]
